### ISSUE TITLE
git-cola error when launching: unhashable type: 'PyQt5.QtCore.pyqtBoundSignal'

### ISSUE THREAD

**Issue by stkw0** [git-cola/git-cola#1101]
```
Traceback (most recent call last):
  File "/usr/bin/git-cola", line 42, in <module>
    sys.exit(main())
  File "/usr/share/git-cola/lib/cola/main.py", line 27, in main
    return args.func(args)
  File "/usr/share/git-cola/lib/cola/main.py", line 452, in cmd_cola
    view = MainView(context)
  File "/usr/share/git-cola/lib/cola/widgets/main.py", line 100, in __init__
    fn=lambda dock: status.StatusWidget(context, dock.titleBarWidget(), dock),
  File "/usr/share/git-cola/lib/cola/qtutils.py", line 813, in create_dock
    widget = fn(dock)
  File "/usr/share/git-cola/lib/cola/widgets/main.py", line 100, in <lambda>
    fn=lambda dock: status.StatusWidget(context, dock.titleBarWidget(), dock),
  File "/usr/share/git-cola/lib/cola/widgets/status.py", line 49, in __init__
    self.tree = StatusTreeWidget(context, parent=self)
  File "/usr/share/git-cola/lib/cola/widgets/status.py", line 284, in __init__
    self.m.add_observer(self.m.message_about_to_update, self.about_to_update.emit)
  File "/usr/share/git-cola/lib/cola/observable.py", line 16, in add_observer
    observers.add(observer)
TypeError: unhashable type: 'PyQt5.QtCore.pyqtBoundSignal'
```

Seems that the error only happens with PyQt5 v5.15.1, with 5.15.0 it works

**Comment by living180** [comment]
This is a known bug in PyQt5 v5.15.1.  See https://www.riverbankcomputing.com/pipermail/pyqt/2020-September/043160.html for details.  It should hopefully be fixed in the next release of PyQt5.

**Comment by davvid** [comment]
Thanks for the heads-up, let's close this for now.

@stkw0 did you get pyqt through your distro, or did you build it yourself?  If distro, it might be worth reporting it upstream so that they can prepare a pyqt update.
