### ISSUE TITLE
TypeError: cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by stkw0** [git-cola/git-cola#1102]
when building with --use-env-python I get the next error
```running build_scripts
creating build/scripts-3.7
Traceback (most recent call last):
  File "setup.py", line 137, in <module>
    main()
  File "setup.py", line 82, in main
    data_files=_data_files(),
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.7/distutils/command/build_scripts.py", line 50, in run
    self.copy_scripts()
  File "/usr/lib/python3.7/distutils/command/build_scripts.py", line 89, in copy_scripts
    match = first_line_re.match(first_line)
TypeError: cannot use a string pattern on a bytes-like object
```

Which can be fixed with the next commit

```diff --git a/setup.py b/setup.py
index fa812258..9c1d7df9 100755
--- a/setup.py
+++ b/setup.py
@@ -28,7 +28,7 @@ try:
 except ValueError:
     use_env_python = False
 if use_env_python:
-    build_scripts.first_line_re = re.compile(r'^should not match$')
+    build_scripts.first_line_re = re.compile(rb'^should not match$')

 # Disable installation of the private cola package by passing --no-private-libs or
 # by setting GIT_COLA_NO_PRIVATE_LIBS=1 in th environment.
```

I don't think if it's a git-cola issue or something wrong with my installation. I suppose more people use the --use-env-python so I find it strange that anyone reported this before.

**Comment by davvid** [comment]
Thanks for the heads-up!
