### ISSUE TITLE
git-dag crashes when viewing a commit on systems with FIPS mode enabled

### ISSUE THREAD

**Issue by audreytoskin** [git-cola/git-cola#1157]
When I first navigate to a repository and launch with `git dag`, the DAG seems to be normally responsive. I can move the window around, and scroll through the log and graph, but even though the HEAD commit is selected by default, the Diff pane is empty. And immediately on launch, the terminal does show this traceback:

```
> git dag
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cola/widgets/dag.py", line 857, in thread_end
    self.restore_selection()
  File "/usr/lib/python3.6/site-packages/cola/widgets/dag.py", line 877, in restore_selection
    self.notifier.notify_observers(diff.COMMITS_SELECTED, [commit_obj])
  File "/usr/lib/python3.6/site-packages/cola/observable.py", line 31, in notify_observers
    method(*args, **opts)
  File "/usr/lib/python3.6/site-packages/cola/widgets/diff.py", line 1096, in commits_selected
    self.set_details(oid, author, email, '', summary)
  File "/usr/lib/python3.6/site-packages/cola/widgets/diff.py", line 1116, in set_details
    self.gravatar_label.set_email(email)
  File "/usr/lib/python3.6/site-packages/cola/gravatar.py", line 57, in set_email
    self.request(email)
  File "/usr/lib/python3.6/site-packages/cola/gravatar.py", line 60, in request
    url = Gravatar.url_for_email(email, self.imgsize)
  File "/usr/lib/python3.6/site-packages/cola/gravatar.py", line 21, in url_for_email
    email_hash = core.decode(hashlib.md5(core.encode(email)).hexdigest())
ValueError: [digital envelope routines: EVP_DigestInit_ex] disabled for FIPS
```

If I click or double-click on the latest commit to try to see the diff, nothing happens. If I click on any other commit in the log, the DAG crashes and closes (exit code 134), with another slightly different traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cola/widgets/dag.py", line 507, in selection_changed
    self.notifier.notify_observers(diff.COMMITS_SELECTED, [i.commit for i in items])
  File "/usr/lib/python3.6/site-packages/cola/observable.py", line 31, in notify_observers
    method(*args, **opts)
  File "/usr/lib/python3.6/site-packages/cola/widgets/diff.py", line 1096, in commits_selected
    self.set_details(oid, author, email, '', summary)
  File "/usr/lib/python3.6/site-packages/cola/widgets/diff.py", line 1116, in set_details
    self.gravatar_label.set_email(email)
  File "/usr/lib/python3.6/site-packages/cola/gravatar.py", line 57, in set_email
    self.request(email)
  File "/usr/lib/python3.6/site-packages/cola/gravatar.py", line 60, in request
    url = Gravatar.url_for_email(email, self.imgsize)
  File "/usr/lib/python3.6/site-packages/cola/gravatar.py", line 21, in url_for_email
    email_hash = core.decode(hashlib.md5(core.encode(email)).hexdigest())
ValueError: [digital envelope routines: EVP_DigestInit_ex] disabled for FIPS
error: git-dag died of signal 6
```

This is 100% reproducible on my machine, so Git DAG is basically unusable for me on this machine.

If you aren't familiar with FIPS mode, Mozilla has a [decent description](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/FIPS_Mode_-_an_explanation), but for our purposes, basically it's a set of security settings which block applications from using weak cryptographic algorithms. So, what I think is happening is that FIPS doesn't "know" that md5 hashes in git commits aren't really meant to be cryptographically secure, and is blocking DAG from working with MD5.

If so, I think DAG _might_ be able to work around it with a relatively small change: Another project deals with a similar problem, in issue s3tools/s3cmd#1005... Looks like they might have gotten around it by changing the `hashlib.md5()` method, simply adding an argument so that it becomes `hashlib.md5(usedforsecurity=False)`.

I'm not really a programmer, so I don't know how much the discussion in that thread could apply to Git Cola. It's weird to me, for example, that DAG crashes with a FIPS error just from trying to view commits, while Cola seems to have no issue pushing/pulling/staging/stashing/committing... But hopefully this at least gets y'all on the right track. 

My system setup:

- CentOS 8 Linux, x86_64, FIPS mode enabled and required at my workplace.
- GNOME Shell 3.32.2
- git-cola / git-dag 3.10.1
- Git 2.27.0
- python3-qt5 5.13.1
- Qt 5.12.5
- Python 3.6.8

**Comment by davvid** [comment]
Thanks for the heads-up. It sounds like this is a new feature that can be enabled in python 3.9, but centos/rhel may have backported this feature to the python3.6 interpreter you're using.

This is the kinda thing that makes me consider vendoring a copy of:
https://gist.github.com/HoLyVieR/11e464a91b290e33b38e

Otherwise we'll have to have a series of try/catch attempts to do it. It's worth handling internally though.

We don't use md5 for security purposes so our usage is safe. I think for now I'll add the `usedforsecurity=False` attempt as a fallback that only kicks in when python > 3.6.

**Comment by davvid** [comment]
Related links in case others end up here via google:

* https://github.com/python/cpython/pull/16044
* https://bugs.python.org/issue9216
