### ISSUE TITLE
StageOrUnstage Exception

### ISSUE THREAD

**Issue by georf** [git-cola/git-cola#1189]
When I merge a branch with a changed image I get an merge conflict. 

For example:
```
warning: Cannot merge binary files: spec/fixtures/screenshots/storybook-1.png (HEAD vs. 6286/excel_import)
Auto-merging spec/fixtures/screenshots/storybook-1.png
CONFLICT (content): Merge conflict in spec/fixtures/screenshots/storybook-1.png
```

Then I start git-cola and try to stage the png file with keyboard by pressing *CTRL*+*s*. I get the following error:

```
Traceback (most recent call last):

  File "/usr/share/git-cola/lib/cola/cmds.py", line 2615, in do
    return cmd.do()

  File "/usr/share/git-cola/lib/cola/cmds.py", line 2289, in do
    unmerged = check_conflicts(self.context, s.unmerged)

  File "/usr/share/git-cola/lib/cola/cmds.py", line 2117, in check_conflicts
    unmerged = [path for path in unmerged if is_conflict_free(path)]

  File "/usr/share/git-cola/lib/cola/cmds.py", line 2117, in <listcomp>
    unmerged = [path for path in unmerged if is_conflict_free(path)]

  File "/usr/share/git-cola/lib/cola/cmds.py", line 2127, in is_conflict_free
    for line in f:

  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```
![Auswahl_044](https://user-images.githubusercontent.com/361453/143427828-2e196b31-b1b3-4b09-a9c0-ee6f0498fc5e.png)

When I use the right mouse menu and select *Stage Selected* it works without trouble.

```
Git Cola version 3.6 
Linux-5.4.0-90-generic-x86_64-with-glibc2.29 
Python (/usr/bin/python3) 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0] 
Git 2.25.1 
Qt 5.12.8 
QtPy 1.9.0 
PyQt5 5.14.1 
```

**Comment by davvid** [comment]
Thanks for the heads-up!
