### ISSUE TITLE
Outdated qtpy doesn't support PyQt6 on M1 Mac

### ISSUE THREAD

**Issue by nyanpasu64** [git-cola/git-cola#1211]
I tried installing git-cola using pipx on Nix Python (don't ask, I kinda regret it). However it didn't install a Qt binding by default, and Qt 5 doesn't support M1 Mac. Running `pipx inject git-cola PyQt6` installed the package (as shown by `pipx runpip git-cola list`), but git cola can't pick it up. And running `QT_API=pyqt6 git-cola` results in error:

```
Traceback (most recent call last):
  File "/Users/nyanpasu64/.local/bin/git-cola", line 40, in <module>
    from cola.main import main
  File "/Users/nyanpasu64/.local/pipx/venvs/git-cola/share/git-cola/lib/cola/main.py", line 6, in <module>
    from . import app
  File "/Users/nyanpasu64/.local/pipx/venvs/git-cola/share/git-cola/lib/cola/app.py", line 16, in <module>
    from qtpy import QtCore
  File "/Users/nyanpasu64/.local/pipx/venvs/git-cola/share/git-cola/lib/qtpy/__init__.py", line 112, in <module>
    assert API in (PYQT5_API + PYQT4_API + PYSIDE_API + PYSIDE2_API)
AssertionError
```

The error persists after installing git-cola HEAD using `pipx install git+https://github.com/git-cola/git-cola.git --force`.

It seems your vendored https://github.com/git-cola/git-cola/blob/main/qtpy/__init__.py is quite outdated and predates PyQt6/PySide6. Can you update qtpy to a newer version?

**Comment by davvid** [comment]
Try installing with `--no-vendor-libs` or try setting `GIT_COLA_NO_VENDOR_LIBS=1` in your environment.

Long story short -- we have a slightly older vendored qtpy. You should be able to delete the installed (in the pipx/ area) `qtpy` directory and then use pipx to install the latest qtpy.

That should make things work. IIRC the latest qtpy versions support M1. We're about to drop python3 support. I'm leaning towards no longer vendoring qtpy in the near future (before the next major release, v4.0.0).

**Comment by nyanpasu64** [comment]
Ran into this issue.

```
nyanpasu64@mba> git cola
Traceback (most recent call last):
  File "/Users/nyanpasu64/.local/bin/git-cola", line 40, in <module>
    from cola.main import main
  File "/Users/nyanpasu64/.local/pipx/venvs/git-cola/share/git-cola/lib/cola/main.py", line 6, in <module>
    from . import app
  File "/Users/nyanpasu64/.local/pipx/venvs/git-cola/share/git-cola/lib/cola/app.py", line 45, in <module>
    from .widgets import cfgactions
  File "/Users/nyanpasu64/.local/pipx/venvs/git-cola/share/git-cola/lib/cola/widgets/cfgactions.py", line 10, in <module>
    from .. import icons
  File "/Users/nyanpasu64/.local/pipx/venvs/git-cola/share/git-cola/lib/cola/icons.py", line 9, in <module>
    from . import qtcompat
  File "/Users/nyanpasu64/.local/pipx/venvs/git-cola/share/git-cola/lib/cola/qtcompat.py", line 9, in <module>
    from . import hotkeys
  File "/Users/nyanpasu64/.local/pipx/venvs/git-cola/share/git-cola/lib/cola/hotkeys.py", line 12, in <module>
    STAGE_MODIFIED = hotkey(Qt.ALT + Qt.Key_A)
TypeError: unsupported operand type(s) for +: 'Modifier' and 'Key'
```

https://github.com/napari/napari/issues/3741 says it's from Python 3.10. I think it's from using PyQt6 which has some incompatible changes.

I had to change a whole pile of things in the code to make it run (use `|` instead of `+` for keyboard shortcuts, use `TYPE = QtGui.QStandardItem.UserType.value + 1` as an integer, QApplication.desktop() was removed so I pretended the screen resolution was 1920x1080, I might've missed more). I'm not sure if you can make the same code run on PyQt5 and 6.

If I want a proper patch with everything I changed, I'd have to try fixing Git Cola in a git clone (with `git diff`) rather than editing my installed pipx package in place. I don't know when I'll do that.

**Comment by yellowsoar** [comment]
@nyanpasu64 
After upgrading to version 4.0.4, I got the same error on my intel-based Mac.
https://github.com/Homebrew/homebrew-core/blob/3dfe90dfad30c81007345ffaa9a03c30723f86b3/Formula/git-cola.rb
So I install `git-cola` via `pipx` with Python 3.9 and that works for me.
BTW, the version of QtPy that `pipx` installed is 2.3.0.

**Comment by davvid** [comment]
Thanks for the heads-up. Please test the latest in git -- PyQt6 is now officially supported.
