### ISSUE TITLE
Cannot launch on Windows

### ISSUE THREAD

**Issue by TypeDefinition** [git-cola/git-cola#1227]
On a fresh install of Windows 10, running git-cola by clicking on the start-menu icon does nothing.

Running via `cmd` produces this error.
```
Traceback (most recent call last):
  File "C:\Program Files\git-cola\pkgs\qtpy\__init__.py", line 210, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Program Files\git-cola\bin\git-cola.exe\__main__.py", line 21, in <module>
  File "C:\Program Files\git-cola\pkgs\cola\main.py", line 6, in <module>
    from . import app
  File "C:\Program Files\git-cola\pkgs\cola\app.py", line 16, in <module>
    from qtpy import QtCore
  File "C:\Program Files\git-cola\pkgs\qtpy\__init__.py", line 216, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
```

I already have the necessary dependencies installed.
```
C:\Users\TypeDefinition>pip list
Package    Version
---------- -------
packaging  21.3
pip        22.0.4
pyparsing  3.0.8
PyQt5      5.15.6
PyQt5-Qt5  5.15.2
PyQt5-sip  12.10.1
QtPy       2.1.0
setuptools 58.1.0
```

**Comment by davvid** [comment]
I'm about to release a new version with a fixed installer that should fix things (if you're using the installer). There were some DLL issues related to https://github.com/takluyver/pynsist/issues/176 that I'm working around by using an older version of Python and PyQt5. I'm able to launch it on Windows 10 now, so hopefully that helps for you.

To debug it, `import PyQt5.QtCore` and then debug the `QtCore.pyd` file using Dependency Walker (as noted in the pynsist docs / issues).

I'm about to push a new commit that updates `pynsist.cfg` with the locked-down versions. That'll resolve this issue, and then I'll be uploading a new installer shortly.

**Comment by TypeDefinition** [comment]
Thanks!
