### ISSUE TITLE
[MacOS] TypeError in hotkeys.py

### ISSUE THREAD

**Issue by werkshy** [git-cola/git-cola#1273]
Version 4.0.4 on MacOS via Homebrew. When launching Cola, it crashes on launch in hotkeys.py:

```
$ git cola 
Traceback (most recent call last):
  File "/usr/local/bin/git-cola", line 5, in <module>
    from cola.main import main
  File "/usr/local/Cellar/git-cola/4.0.4/libexec/lib/python3.11/site-packages/cola/main.py", line 6, in <module>
    from . import app
  File "/usr/local/Cellar/git-cola/4.0.4/libexec/lib/python3.11/site-packages/cola/app.py", line 47, in <module>
    from .widgets import cfgactions
  File "/usr/local/Cellar/git-cola/4.0.4/libexec/lib/python3.11/site-packages/cola/widgets/cfgactions.py", line 10, in <module>
    from .. import icons
  File "/usr/local/Cellar/git-cola/4.0.4/libexec/lib/python3.11/site-packages/cola/icons.py", line 9, in <module>
    from . import qtcompat
  File "/usr/local/Cellar/git-cola/4.0.4/libexec/lib/python3.11/site-packages/cola/qtcompat.py", line 9, in <module>
    from . import hotkeys
  File "/usr/local/Cellar/git-cola/4.0.4/libexec/lib/python3.11/site-packages/cola/hotkeys.py", line 12, in <module>
    STAGE_MODIFIED = hotkey(Qt.ALT + Qt.Key_A)
                            ~~~~~~~^~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'Modifier' and 'Key'
```

I am a bit surprised to be the first to report this - it makes me worry that there's something wrong with my environment but I have tried to rule that out. I have pyqt@5 and python@3.11 installed and update via brew. I've tried uninstall/reinstall; and installing --HEAD version of git-cola.

**Comment by werkshy** [comment]
Ah, I just found https://github.com/git-cola/git-cola/issues/1211 which indicates that this is pyqt6-related, so perhaps this is more of a bug in the brew package.

**Comment by davvid** [comment]
The hotkeys were also an issue when going between PyQt5 and PySide2, so it'll be good to get this working. I just reproduced this locally. I'm going through and changing those `+`'s to `|`'s and that seems to be what's needed (so far...).

That seems to be backwards-compatible. Qt6 deprecated the `+` operator. I'll use this issue as motivation for getting this working in Qt6.

The install_requires stuff in the python packaging files is unfortunate. The code will still be compatible with Qt5, but setup.cfg isn't able to express the "I can work with either one" so I won't change that part, but I'll make the code compatible.

**Comment by davvid** [comment]
That wasn't that bad. Thanks for the heads-up. Please test the latest in git -- PyQt6 is now supported.

**Comment by werkshy** [comment]
@davvid thanks! Confirmed working with `brew install --HEAD git-cola` (5ef599d).
