### ISSUE TITLE
Execute failure with TypeError when running git cola

### ISSUE THREAD

**Issue by xis19** [git-cola/git-cola#1279]
I am seeing 

```python
Traceback (most recent call last):
  File "/usr/local/bin/git-cola", line 5, in <module>
    from cola.main import main
  File "/usr/local/Cellar/git-cola/4.0.4/libexec/lib/python3.11/site-packages/cola/main.py", line 6, in <module>
    from . import app
  File "/usr/local/Cellar/git-cola/4.0.4/libexec/lib/python3.11/site-packages/cola/app.py", line 47, in <module>
    from .widgets import cfgactions
  File "/usr/local/Cellar/git-cola/4.0.4/libexec/lib/python3.11/site-packages/cola/widgets/cfgactions.py", line 10, in <module>
    from .. import icons
  File "/usr/local/Cellar/git-cola/4.0.4/libexec/lib/python3.11/site-packages/cola/icons.py", line 9, in <module>
    from . import qtcompat
  File "/usr/local/Cellar/git-cola/4.0.4/libexec/lib/python3.11/site-packages/cola/qtcompat.py", line 9, in <module>
    from . import hotkeys
  File "/usr/local/Cellar/git-cola/4.0.4/libexec/lib/python3.11/site-packages/cola/hotkeys.py", line 12, in <module>
    STAGE_MODIFIED = hotkey(Qt.ALT + Qt.Key_A)
                            ~~~~~~~^~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'Modifier' and 'Key'
```

when running

```bash
git cola
```

I am using git-cola 4.0.4 with Python3.11 and Qt 6.4.1_1

**Comment by davvid** [comment]
If you have PyQt5 available it won't run into this issue using your current version. If you have PyQt6 and PyQt5 installed you can `export QT_API=pyqt5` in your environment to ensure that it uses that version.

These issues have already been fixed.

Please see 72d5244700b4c8b264b38ecb17e7dbf84487fec8 961b2a3d7f7c2d4b37b12cc8717e65fbfec6ce48 and 6018ab30ce06d9db81fdb3351901e60447389b38 which added support for PyQt6.

The fixes will be released soon in v4.1.0. Thanks for the heads-up.
