### ISSUE TITLE
After upgrade failed to start on Ubuntu 22.10

### ISSUE THREAD

**Issue by mrquokka** [git-cola/git-cola#1304]
```
git cola

You do not seem to have PyQt (or PySide) and qtpy installed.
Please install the PyQt (or PySide) and qtpy into your Python environment.

For example, on a Debian/Ubuntu system you can install these using apt:

    sudo apt install python3-pyqt5 python3-pyqt5.qtwebkit python3-qtpy
```

git-cola version (3.12.0-1)
python3-pyqt5 (5.15.7+dfsg-1build1).
python3-pyqt5.qtwebkit (5.15.7+dfsg-1build1).
python3-qtpy (2.1.0-4).

Tried to remove apt and install from pip some errror (git-cola 4.x version)
If i remove apt packages for qt5 and try from pip

```
Requirement already satisfied: pyqt5 in /usr/lib/python3/dist-packages (5.15.7)
Collecting pyqt5
  Downloading PyQt5-5.15.9.tar.gz (3.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 13.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      Traceback (most recent call last):
        File "/usr/local/lib/pypy3.8/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 156, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/usr/local/lib/pypy3.8/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/local/lib/pypy3.8/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/pypy3.8/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 160, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/tmp/pip-build-env-bxukavtp/overlay/lib/pypy3.8/site-packages/sipbuild/api.py", line 47, in build_wheel
          arguments=_convert_config_settings(config_settings))
        File "/tmp/pip-build-env-bxukavtp/overlay/lib/pypy3.8/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/tmp/pip-build-env-bxukavtp/overlay/lib/pypy3.8/site-packages/sipbuild/project.py", line 585, in setup
          self.apply_user_defaults(tool)
        File "project.py", line 68, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/tmp/pip-build-env-bxukavtp/overlay/lib/pypy3.8/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/tmp/pip-build-env-bxukavtp/overlay/lib/pypy3.8/site-packages/sipbuild/project.py", line 236, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/tmp/pip-build-env-bxukavtp/overlay/lib/pypy3.8/site-packages/pyqtbuild/builder.py", line 70, in apply_user_defaults
          "specify a working qmake or add it to PATH")
      sipbuild.pyproject.PyProjectOptionException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

If i try upgrade system pip and try install pyqt5

```
Collecting pyqt5
  Using cached PyQt5-5.15.9.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "/usr/local/lib/pypy3.8/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/pypy3.8/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/pypy3.8/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/tmp/pip-build-env-ydbo2tbt/overlay/lib/pypy3.8/site-packages/sipbuild/api.py", line 47, in build_wheel
          arguments=_convert_config_settings(config_settings))
        File "/tmp/pip-build-env-ydbo2tbt/overlay/lib/pypy3.8/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/tmp/pip-build-env-ydbo2tbt/overlay/lib/pypy3.8/site-packages/sipbuild/project.py", line 585, in setup
          self.apply_user_defaults(tool)
        File "project.py", line 68, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/tmp/pip-build-env-ydbo2tbt/overlay/lib/pypy3.8/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/tmp/pip-build-env-ydbo2tbt/overlay/lib/pypy3.8/site-packages/sipbuild/project.py", line 236, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/tmp/pip-build-env-ydbo2tbt/overlay/lib/pypy3.8/site-packages/pyqtbuild/builder.py", line 70, in apply_user_defaults
          "specify a working qmake or add it to PATH")
      sipbuild.pyproject.PyProjectOptionException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

**Comment by davvid** [comment]
Use your system package manager. Never `pip` as root or undo `sudo`. Never run `pip` outside of a virtualenv.

Your python setup might be busted, but it's impossible to tell based on your the provided output. You didn't even provide the commands you ran. I say "busted" because I see a bunch of `/usr/local` paths, which suggests to me that pip wrote a bunch of broken modules there and you'd have to manually clean things up if you want to make things stable again.

Please read the README.md carefully and try running using your system-provied PyQt5 packages or a virtualenv.

**Comment by mrquokka** [comment]
> Use your system package manager. Never `pip` as root or undo `sudo`. Never run `pip` outside of a virtualenv.
> 
> Your python setup might be busted, but it's impossible to tell based on your the provided output. You didn't even provide the commands you ran. I say "busted" because I see a bunch of `/usr/local` paths, which suggests to me that pip wrote a bunch of broken modules there and you'd have to manually clean things up if you want to make things stable again.
> 
> Please read the README.md carefully and try running using your system-provied PyQt5 packages or a virtualenv.

What? Did you read the issue? I tried from package manager at start and it broken. Tried to fix in manually and i cannot

**Comment by davvid** [comment]
In the future you can try the latest version by just running the `./bin/git-cola` script directly. Trying to install it will run into the pip issues that you ran into.

The fact that reinstalling the OS fixed the issue is evidence that a newer pip and installing pip packages into global system locations is what broke things.

Python has very sharp edges in its packaging space despite the seemingly user-friendly nature of the language.

**Comment by davvid** [comment]
Heads-up that the next Ubuntu versions (after 22) have added safety measures to prevent users from using `pip` to install stuff into `/usr/local`.

https://discuss.python.org/t/pep-668-marking-python-base-environments-as-externally-managed/10302/68?page=4

Using a virtualenv when installing for local use is the only supported paradigm at the moment. In the README.md you'll note that we specifically mention using `python3 -m venv --system-site-packages` so that your system-provided PyQt5 packages end up getting used.

**Comment by mrquokka** [comment]
> In the future you can try the latest version by just running the `./bin/git-cola` script directly. Trying to install it will run into the pip issues that you ran into.
> 
> The fact that reinstalling the OS fixed the issue is evidence that a newer pip and installing pip packages into global system locations is what broke things.
> 
> Python has very sharp edges in its packaging space despite the seemingly user-friendly nature of the language.

I tried it from last version, and from master - same error. Anyway - i reinstall OS and cannot reproduce problem now
