### ISSUE TITLE
build broken by toml change

### ISSUE THREAD

**Issue by sthalik** [git-cola/git-cola#1324]
```console
f:\dev\git-cola>setup.py install
Traceback (most recent call last):
  File "F:\dev\git-cola\setup.py", line 5, in <module>
    setuptools.setup()
  File "C:\Python3\Lib\site-packages\setuptools\__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3\Lib\site-packages\setuptools\_distutils\core.py", line 159, in setup
    dist.parse_config_files()
  File "C:\Python3\Lib\site-packages\setuptools\dist.py", line 868, in parse_config_files
    pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
  File "C:\Python3\Lib\site-packages\setuptools\config\pyprojecttoml.py", line 62, in apply_configuration
    config = read_configuration(filepath, True, ignore_option_errors, dist)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3\Lib\site-packages\setuptools\config\pyprojecttoml.py", line 98, in read_configuration
    asdict = load_file(filepath) or {}
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Python3\Lib\site-packages\setuptools\config\pyprojecttoml.py", line 30, in load_file
    return tomli.load(file)
           ^^^^^^^^^^^^^^^^
  File "C:\Python3\Lib\site-packages\setuptools\_vendor\tomli\_parser.py", line 66, in load
    return loads(s, parse_float=parse_float)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3\Lib\site-packages\setuptools\_vendor\tomli\_parser.py", line 102, in loads
    pos = key_value_rule(src, pos, out, header, parse_float)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3\Lib\site-packages\setuptools\_vendor\tomli\_parser.py", line 349, in key_value_rule
    raise suffixed_err(src, pos, "Cannot overwrite a value")
setuptools._vendor.tomli.TOMLDecodeError: Cannot overwrite a value (at line 21, column 2)
```

Python versions: 3.10 and 3.11 on Windows.

Known good commit: 37ff2b12 (tag v4.2.1)

**Comment by davvid** [comment]
I shouldn't have merged #1309. Hmm..

I don't use either of these two tools, but it seems like poetry requires a [single single string value](https://python-poetry.org/docs/pyproject/#authors) and flit requires [separate name and author fields](https://flit.pypa.io/en/latest/pyproject_toml.html#new-style-metadata).

The goof is that the PR made it use use both, oops.

I'll revert  the changes from #1309. Thanks for the heads-up.
