### ISSUE TITLE
pipx install won't run

### ISSUE THREAD

**Issue by brccabral** [git-cola/git-cola#1350]
$ pipx install git-cola
$ git-cola
Traceback (most recent call last):
  File "/home/brccabral/.local/bin/git-cola", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/brccabral/.local/pipx/venvs/git-cola/lib/python3.11/site-packages/cola/main.py", line 28, in main
    return args.func(args)
           ^^^^^^^^^^^^^^^
  File "/home/brccabral/.local/pipx/venvs/git-cola/lib/python3.11/site-packages/cola/main.py", line 465, in cmd_cola
    context = app.application_init(args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/brccabral/.local/pipx/venvs/git-cola/lib/python3.11/site-packages/cola/app.py", line 329, in application_init
    context = new_context(args)
              ^^^^^^^^^^^^^^^^^
  File "/home/brccabral/.local/pipx/venvs/git-cola/lib/python3.11/site-packages/cola/app.py", line 350, in new_context
    context.fsmonitor = fsmonitor.create(context)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/brccabral/.local/pipx/venvs/git-cola/lib/python3.11/site-packages/cola/fsmonitor.py", line 514, in create
    if not cfg.get('cola.inotify', default=True):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/brccabral/.local/pipx/venvs/git-cola/lib/python3.11/site-packages/cola/gitcfg.py", line 225, in get
    return self._get(self._all, key, default, func=func, cached=cached)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/brccabral/.local/pipx/venvs/git-cola/lib/python3.11/site-packages/cola/gitcfg.py", line 198, in _get
    self.update()
  File "/home/brccabral/.local/pipx/venvs/git-cola/lib/python3.11/site-packages/cola/gitcfg.py", line 161, in update
    for current_scope, current_key, current_value, continuation in reader(
  File "/home/brccabral/.local/pipx/venvs/git-cola/lib/python3.11/site-packages/cola/gitcfg.py", line 611, in _read_config_fallback
    if os.path.exists(local_config):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by davvid** [comment]
That is super interesting and this is the only time I've seen that code error-out. I'm very curious to try to reproduce it but in my environment it always launches the "select a git repository" dialog.

Do you happen to have a `.git` directory in the current directory from which you launched it?

Thanks for the report nonetheless. I'm going to add another safety check to make sure it can't even hit that.
