### ISSUE TITLE
 Crash opening a project stored on a WSL1 filesystem (Windows 11)

### ISSUE THREAD

**Issue by Hoernchen** [git-cola/git-cola#1441]
https://github.com/git-cola/git-cola/issues/1194 is still happening on WSL**1**  with 4.9.0

```
>/mnt/c/Program\ Files/git-cola/bin/git-cola.exe
qt.qpa.fonts: Unable to enumerate family ' "Droid Sans Mono Dotted for Powerline" '
qt.qpa.fonts: Unable to enumerate family ' "Droid Sans Mono Slashed for Powerline" '
qt.qpa.fonts: Unable to enumerate family ' "Roboto Mono Medium for Powerline" '
qt.qpa.fonts: Unable to enumerate family ' "Ubuntu Mono derivative Powerline" '
Traceback (most recent call last):
  File "C:\Program Files\git-cola\pkgs\cola\fsmonitor.py", line 467, in run
    status = win32event.WaitForMultipleObjects(events, False, timeout)
pywintypes.error: (6, 'WaitForMultipleObjects', 'The handle is invalid.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\git-cola\pkgs\cola\fsmonitor.py", line 480, in run
    self._worktree_watch.close()
  File "C:\Program Files\git-cola\pkgs\cola\fsmonitor.py", line 414, in close
    win32file.CancelIo(self.handle)
pywintypes.error: (6, 'CancelIo', 'The handle is invalid.')
```

The described workaround still works.

**Comment by davvid** [comment]
Please test out the installer from https://github.com/git-cola/git-cola/actions/runs/12221653177 and let me know if that improves things in your setup.

**Comment by davvid** [comment]
Cool, we're on the right track. There's a new build that addresses the ones in the error message you posted. Let me know how that goes.

https://github.com/git-cola/git-cola/actions/runs/12289211178

**Comment by Hoernchen** [comment]
Yes, that appears to have fixed it. Thanks! Now, on to the next issue...
