### ISSUE TITLE
Browse Other Branch doesn't work

### ISSUE THREAD

**Issue by andrewcchen** [git-cola/git-cola#501]
No dialogue opens.
This is logged to the console:
```
Traceback (most recent call last):
  File "/usr/share/git-cola/lib/cola/guicmds.py", line 49, in browse_current
    BrowseDialog.browse(branch)
  File "/usr/share/git-cola/lib/cola/widgets/browse.py", line 411, in browse
    dlg_model = GitTreeModel(ref, dlg)
  File "/usr/share/git-cola/lib/cola/widgets/browse.py", line 649, in __init__
    self._initialize()
  File "/usr/share/git-cola/lib/cola/widgets/browse.py", line 670, in _initialize
    self.add_directory(parent, relpath)
  File "/usr/share/git-cola/lib/cola/widgets/browse.py", line 606, in add_directory
    row = self.dir_rows[parent]
TypeError: unhashable type: 'QStandardItem'
```

**Comment by davvid** [comment]
Interesting. I wonder if this is a Python3 or newer-PyQt4 thing.  Do you know what version of PyQt4 you're using? We might have to workaround this, but should be doable. Interestingly, it seems to be okay here (debian/sid).  I've included a short python transcript below showing how to get it.

```
$ python
Python 2.7.10 (default, Jun  1 2015, 16:21:46) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt4.QtCore import PYQT_VERSION_STR
>>> PYQT_VERSION_STR
'4.11.4'
```

**Comment by andrewcchen** [comment]
Oh, sorry, forgot to mention my software versions. I am using python3, so that might be the problem.
OS: Arch Linux
```
$ python
Python 3.4.3 (default, Sep  7 2015, 15:40:35) 
[GCC 5.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt4.QtCore import PYQT_VERSION_STR
>>> PYQT_VERSION_STR
'4.11.4'
```
```
$ pacman -Q qt4 python-pyqt4 python
qt4 4.8.7-2
python-pyqt4 4.11.4-1
python 3.4.3-3
```
