### ISSUE TITLE
Build fail with UnicodeDecodeError: ordinal not in range(128) in extras/build_mo.py <del>when source dir is under CJK path</del>

### ISSUE THREAD

**Issue by Vdragon** [git-cola/git-cola#551]
Encountered this issue when testing PR #549 

## Steps to Reproduce Issue
1. ~~Create folder named "中文路徑"~~
1. ~~Copy source folder under "中文路徑" folder~~
1. Run `make` ~~under the new source folder~~

**UPDATE:** It seems that the issue can be reproduced even on encoding-safe path, like `/tmp/gitcola`

## Build Log
```
python setup.py build
running build
running build_mo
Traceback (most recent call last):
  File "setup.py", line 78, in <module>
    main()
  File "setup.py", line 44, in main
    data_files = cola_data_files())
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/tmp/中文路徑/gitcola/extras/build_mo.py", line 66, in run
    if find_executable('msgfmt') is None:
  File "/usr/lib/python2.7/distutils/spawn.py", line 220, in find_executable
    f = os.path.join(p, executable)
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 14: ordinal not in range(128)
Makefile:77: recipe for target 'build' failed
make: *** [build] Error 1

```

### Operating System
Ubuntu 15.10 AMD64

### Locale
```bash
LANG=zh_TW.UTF-8
LANGUAGE=zh_TW:zh_HK:zh_CN:en_US:en
LC_CTYPE="zh_TW.UTF-8"
LC_NUMERIC=zh_TW.UTF-8
LC_TIME=zh_TW.UTF-8
LC_COLLATE="zh_TW.UTF-8"
LC_MONETARY=zh_TW.UTF-8
LC_MESSAGES="zh_TW.UTF-8"
LC_PAPER=zh_TW.UTF-8
LC_NAME=zh_TW.UTF-8
LC_ADDRESS=zh_TW.UTF-8
LC_TELEPHONE=zh_TW.UTF-8
LC_MEASUREMENT=zh_TW.UTF-8
LC_IDENTIFICATION=zh_TW.UTF-8
LC_ALL=
```

### Git Cola
commit 3a5c09fe

**Comment by davvid** [comment]
I have a fix.  Thanks for testing the other MR.  I'll merge that one now and I'll have a fix for this shortly
