### ISSUE TITLE
Git-Cola can not be started a second time

### ISSUE THREAD

**Issue by ohaessler** [git-cola/git-cola#591]
I have user reports on Fedora 24 that say that if you start git-cola a second time, you get the following error message:

Traceback (most recent call last): File "/usr/bin/cola", line 56, in <module> sys.exit(main()) File "/usr/share/git-cola/lib/cola/main.py", line 37, in main return args.func(args) File "/usr/share/git-cola/lib/cola/main.py", line 282, in cmd_cola view = MainView(context.model, settings=args.settings) File "/usr/share/git-cola/lib/cola/widgets/main.py", line 508, in __init__ self.init_state(settings, self.set_initial_size) File "/usr/share/git-cola/lib/cola/widgets/standard.py", line 102, in init_state if not self.restore_state(settings=settings): File "/usr/share/git-cola/lib/cola/widgets/standard.py", line 57, in restore_state return bool(state) and self.apply_state(state) File "/usr/share/git-cola/lib/cola/widgets/main.py", line 651, in apply_state result = standard.MainWindow.apply_state(self, state) File "/usr/share/git-cola/lib/cola/widgets/standard.py", line 133, in apply_state from_base64(str(windowstate)), TypeError: arguments did not match any overloaded call: fromBase64(Union[QByteArray, bytes, bytearray]): argument 1 has unexpected type 'str' fromBase64(Union[QByteArray, bytes, bytearray], Union[QByteArray.Base64Options, QByteArray.Base64Option]): argument 1 has unexpected type 'str'

and git-cola does not start.

**Comment by ohaessler** [comment]
fixed in git-cola 2.8

**Comment by danielkza** [comment]
@ohaessler Do you happen to know which commit fixed it? I'

**Comment by davvid** [comment]
@danielkza the QBytesArray PyQt5-incompatibility was fixed in 31dd6fa7e49e787bcc18f800dc7b03f938f64b43
