### ISSUE TITLE
NameError: global name 'wd_to_path_set' is not defined

### ISSUE THREAD

**Issue by joshuataylor** [git-cola/git-cola#607]
Ubuntu 16.04, using xubuntu (if that matters)

```
Traceback (most recent call last):

  File "cola/cmds.py", line 1865, in do_cmd
    return cmd.do()

  File "cola/cmds.py", line 1267, in do
    fsmonitor.current().refresh()

  File "cola/fsmonitor.py", line 73, in refresh
    self._thread.refresh()

  File "cola/fsmonitor.py", line 240, in refresh
    self._worktree_path_to_wd_map)

  File "cola/fsmonitor.py", line 263, in _refresh_watches
    wd_to_path_set.pop(wd)

NameError: global name 'wd_to_path_set' is not defined
```

Randomly appears, not sure what triggers it.

**Comment by fabier** [comment]
Traceback (most recent call last):

  File "/home/fabier/share/git-cola/lib/cola/cmds.py", line 1865, in do_cmd
    return cmd.do()

  File "/home/fabier/share/git-cola/lib/cola/cmds.py", line 1267, in do
    fsmonitor.current().refresh()

  File "/home/fabier/share/git-cola/lib/cola/fsmonitor.py", line 73, in refresh
    self._thread.refresh()

  File "/home/fabier/share/git-cola/lib/cola/fsmonitor.py", line 240, in refresh
    self._worktree_path_to_wd_map)

  File "/home/fabier/share/git-cola/lib/cola/fsmonitor.py", line 263, in _refresh_watches
    wd_to_path_set.pop(wd)

NameError: global name 'wd_to_path_set' is not defined

**Comment by davvid** [comment]
This issue was first fixed in `v2.9` back in November 2016.  It's been over a year and we've had a few releases since then, most recently `v3.0`.  If you're hitting this, I would suggest cloning the repo and keeping a symlink to `bin/git-cola` somewhere in your path, e.g. in `~/bin`:

```
mkdir -p ~/src
git clone git://github.com/git-cola/git-cola.git ~/src/git-cola
mkdir -p ~/bin
cd ~/bin
ln -s ../src/git-cola/bin/git-cola
ln -s ../src/git-cola/bin/git-dag
```

Lastly, edit your `~/.bashrc` and make sure that `$HOME/bin` is at the front of the `$PATH` environment variable. Once it's setup then `git cola` will use the version from the cloned repo.  I hope that helps.

The better solution would be to host a git-cola ppa so that users can try newer cola versions on older ubuntu releases.  If someone wants to help, #460 is our issue to track that request.

Thanks for the reminder that we should make it easier for ubuntu users to try new versions.

**Comment by fabier** [comment]
Thank you !
I'll try it as soon as possible.
You’re right i'm on Ubuntu 17.10, but i dont remember thé git cola version
im using.
Thanks a lot.
Regards,
Pierre

Le lun. 20 nov. 2017 02:01, David Aguilar <notifications@github.com> a
écrit :

**Comment by fabier** [comment]
I tried your solution and it works like a charm.
Thanks.
Pierre
