### ISSUE TITLE
Add _text_ drag-and-drop support

### ISSUE THREAD

**Issue by nocnokneo** [git-cola/git-cola#719]
The drag and drop support from the status widget of a file to an e.g. a text editor works great (thanks!) However if I drop the file on an application that only accepts MIME text (e.g. a shell terminal) nothing happens. 

Expected behavior is that the shell terminal receives a quoted path of the file that was dropped. If multiple files are selected and dragged the dropped text should be a space separated list of all the selected files like:

```
"/path/to/file_a" "/path/to/file_b" "/path/to/file_c"
```

**Comment by davvid** [comment]
This'll probably be an interesting one to debug.  In `terminator`, dragging two files from the status widget results in two newline-separated `file://...` urls printed to the terminal.  We also add `text/x-moz-url` mimedata, via qtutils.py's `mimedata_from_paths()`, to allow `gnome-terminal` to operate.. and it creates a shell-friendly space-separated list of quoted files in that mimedata.

Maybe there's more mimedata we can add to handle that case?  We're currently using `setUrls()` and `setData()`.. maybe we need to use `setText()` too?

The encoding was a bummer in the past.  gnome-terminal wanted utf16 while terminator expected utf8, so we have a `cola.dragencoding` knob to control which one to use.  Which terminal?

Our `cola.dragencoding` default is `utf-16`, but maybe the terminal requires `utf-8`?

**Comment by nocnokneo** [comment]
Ah, yes, Now that you mention it, I remember gnome-terminal and other Linux
terminals working well here (except for the fact that the paths were
prefixed with `file://` which I disagreed with).

I'm stuck on Windows at the moment and using the default cmd.exe terminal.
Let me know what info you'd like me to collect to debug the issue.

**Comment by davvid** [comment]
I think this should be better behaved now. I noticed that `kitty` doesn't seem to gracefully handle the QMimeData drops when they contain URLs -- it works fine for a single path but it mashes them together without spaces separating the paths when multiple URLs are selected.

We also had some old cruft in there to support older versions of gnome-terminal. I removed parts that are no longer needed and that cleaned things up a bit. It's simpler and should do the right thing by default for most users now.

For terminals like `kitty` (and possibly `cmd.exe`) that are better off receiving a space-separated list of files I've added support for dragging with the Shift modifier.

If the Shift button is held down when the drag is first initiated then the payload will not contain URLs. It will only contain shell-friendly plain text. This fixes being able to drag multiple file paths into `kitty` and could possibly help `cmd.exe` as well. If `cmd.exe` still does not accept drops after these changes then it's possible that it doesn't accept drops in general.

If `cmd.exe` does accept drops from specific programs then we can follow-up with that. I have a standalone Qt drop target app that can be used to debug drag+drop across apps. We'd debug things by dragging+dropping into the standalone  drop target app from the program that is able to drag+drop onto `cmd.exe`. The standalone drop target app will then tell us what metadata we need to include in order to make `cmd.exe` happy. Anyways, I'm hoping we won't need to go down that route and that the simple `shift-drag` workaround we added for `kitty` is also useful for other shells or tools.

Let me know if it's better behaved now. You'll have to run git-cola from source until the upcoming v4.2.0 is released in order to test it, though. cheers!

**Comment by nocnokneo** [comment]
Thanks for working on this! I tested with Ubuntu 20.04 with gnome-terminal 3.36.2-1ubuntu1~20.04.

> We also had some old cruft in there to support older versions of gnome-terminal. I removed parts that are no longer needed and that cleaned things up a bit. It's simpler and should do the right thing by default for most users now.

This is still not the case for me. Dragging without holding `shift` behaves the same way as before.

> If the Shift button is held down when the drag is first initiated then the payload will not contain URLs. It will only contain shell-friendly plain text.

The `shift+drag` works for one file although the `shift` modifier is an awkward usability problem because you first have to select the one file then hold shift while clicking it. Otherwise `shift` will work to select a range of files in the list.

If I try to `shift+drag` more than one file that were individually selected by `ctrl`+ clicking each one then things work as expected. However, if the multiple files were selected by `shift`+ click first then `shift` + click last then `shift+drag` only drags the first one. I sometimes see this written to stdout when this happens:

```
QAbstractItemModel::endRemoveRows:  Invalid index ( -1 , 0 ) in model QTreeModel(0x3496980)
```

If I try to `shift+drag` files from both the Modified and Untracked sections at the same time then _all_ the Untracked files disappear and the following is output to stdout:

```
Traceback (most recent call last):
  File "/home/tbraunjones/git/git-cola/cola/widgets/status.py", line 532, in _about_to_update
    self._save_selection()
  File "/home/tbraunjones/git/git-cola/cola/widgets/status.py", line 559, in _save_selection
    self.old_selection = self.selection()
  File "/home/tbraunjones/git/git-cola/cola/widgets/status.py", line 976, in selection
    self.staged(), self.unmerged(), self.modified(), self.untracked()
  File "/home/tbraunjones/git/git-cola/cola/widgets/status.py", line 1041, in untracked
    return qtutils.get_selected_values(self, UNTRACKED_IDX, self._model.untracked)
  File "/home/tbraunjones/git/git-cola/cola/qtutils.py", line 1170, in get_selected_values
    return tree_selection(item, values)
  File "/home/tbraunjones/git/git-cola/cola/qtutils.py", line 406, in tree_selection
    count = min(tree_item.childCount(), len(items))
AttributeError: 'NoneType' object has no attribute 'childCount'
Traceback (most recent call last):
  File "/home/tbraunjones/git/git-cola/cola/widgets/status.py", line 566, in refresh
    self._set_untracked(self._model.untracked)
  File "/home/tbraunjones/git/git-cola/cola/widgets/status.py", line 610, in _set_untracked
    self._set_subtree(items, UNTRACKED_IDX, N_('Untracked'), untracked=True)
  File "/home/tbraunjones/git/git-cola/cola/widgets/status.py", line 618, in _set_subtree
    parent.setHidden(hide)
AttributeError: 'NoneType' object has no attribute 'setHidden'
```

File > Refresh does not recover from this. I had to restart git-cola.

**Comment by davvid** [comment]
Thanks for the heads-up. I'll see if there's something we can do to cancel the drag operation when the header items are selected to avoid that error. I'm able to reproduce it.

> The shift+drag works for one file although the shift modifier is an awkward usability problem because you first have to select the one file then hold shift while clicking it

True. I'll change this so that we use the Alt modifier and update during the mouseMoveEvent instead of on click so that it doesn't matter whether it was pressed exactly when clicked.

I just re-tested and here's what I'm seeing.

*gnome-terminal*: I restored the `text/x-moz-url` payload and the associated `cola.dragencoding`, but that didn't seem to make any difference in behavior.

Regular drags seem to do the right thing and paste the values in a way that's command-line friendly. They're quoted and space-separated.

The Alt-drag actually messes stuff up. It looks like gnome-terminal does not like whatever encoding Qt is using in its mimedata when using paths with utf-8 characters. This seems to be a shortcoming with gnome-terminal.

*terminator*: This one seems to behave well in all scenarios. A regular drag results in command-line quoted paths, and an Alt-drag does the same (because it uses the quoted values the Cola produced).

*kitty*: Regular drags are arguably a better default behavior in that multiple paths are newline-separated and are not quoted in any way. They're more "raw" and I can see that being useful when using `cat` to write filenames to a file, etc.

Since the regular drags are newline-separated and not amenable for command-lines, the Alt-drag is useful here because it results in quoted paths that are command-line friendly.

Here are the versions I tested. I'm using gnome on debian/testing and the gnome is running under wayland.

* kitty 0.26.5-4
* gnome-terminal 3.46.7-1
* terminator 2.1.2-1

It's notable that you're on gnome-terminal 3.36 and seeing different behavior. That's a bummer, because I was hoping we could make things better for gnome-terminal since many users will use that terminal. On the plus side, if my testing is correct then it does look like things are already better by default when using newer versions of gnome-terminal.

I'll have to look into the edge case crash around dragging the header items in the next few days unless someone beats me to it. We'll have to somehow make those un-draggable.

Thanks for the quick feedback. I don't have an older gnome-terminal to test against so I'm curious if the text/x-moz-url is better behaved in your setup after the most recent push.

If it's at least no worse than before then hopefully the Alt modifier will be an acceptable workaround until the newer versions are on your horizon.
