### ISSUE TITLE
git-cola crashes with any git repository

### ISSUE THREAD

**Issue by jfessard** [git-cola/git-cola#728]
I just updated and am hitting this issue. I can run it fine in any non-git, but as soon as I point it to a repo, it crashes.
Version: `commit a0fa2c256a90863750ed4adfd2171e65b228607b (HEAD -> master, origin/master, origin/HEAD)`

```
$ git-cola 
Traceback (most recent call last):
  File "~/src/git-cola/bin/git-cola", line 56, in <module>
    sys.exit(main())
  File "~/src/git-cola/cola/main.py", line 31, in main
    return args.func(args)
  File "~/src/git-cola/cola/main.py", line 284, in cmd_cola
    view = MainView(context.model, settings=args.settings)
  File "~/src/git-cola/cola/widgets/main.py", line 126, in __init__
    self.commiteditor = editor = commitmsg.CommitMessageEditor(model, self)
  File "~/src/git-cola/cola/widgets/commitmsg.py", line 87, in __init__
    self.description = CommitMessageTextEdit()
  File "~/src/git-cola/cola/widgets/commitmsg.py", line 574, in __init__
    SpellCheckTextEdit.__init__(self, hint, parent)
  File "~/src/git-cola/cola/widgets/spellcheck.py", line 132, in __init__
    HintedTextEdit.__init__(self, hint, parent)
  File "~/src/git-cola/cola/widgets/text.py", line 568, in __init__
    self.hint = HintWidget(self, hint)
  File "~/src/git-cola/cola/widgets/text.py", line 464, in __init__
    self.enable(True)
  File "~/src/git-cola/cola/widgets/text.py", line 499, in enable
    self._widget.set_value(self._hint, block=True)
  File "~/src/git-cola/cola/widgets/text.py", line 576, in set_value
    TextEdit.set_value(self, value, block=block)
  File "~/src/git-cola/cola/widgets/text.py", line 315, in set_value
    self.ext.set_value(value, block=block)
  File "~/src/git-cola/cola/widgets/text.py", line 116, in set_value
    old_value = self.widget.value()
  File "~/src/git-cola/cola/widgets/text.py", line 312, in value
    return self.ext.value()
  File "~/src/git-cola/cola/widgets/text.py", line 108, in value
    return self._get_value(self.widget)
  File "~/src/git-cola/cola/widgets/text.py", line 405, in get_value_hinted
    hint = widget.hint.value()
AttributeError: 'CommitMessageTextEdit' object has no attribute 'hint'
```

**Comment by davvid** [comment]
This was caused a PyQt4 vs PyQt5 difference, which is why I didn't notice it.  Thanks for the heads-up!

**Comment by davvid** [comment]
This was caused a PyQt4 vs PyQt5 difference, which is why I didn't notice it.  Thanks for the heads-up!

**Comment by jfessard** [comment]
That was fast. Will try it tomorrow! Thanks.
