### ISSUE TITLE
UnicodeDecodeError occurrs in log cursor.insertText(prefix + line + '\n') in "lib/cola/widgets/log.py" when loading a git repository

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [git-cola/git-cola#746]
## Bug Reproducing Instructions
1. Load any existing Git repository or create new repository

## Expected Result
Git Cola loads the repository normally

## Current Result
Git Cola not launched with the following message in console:

```
Traceback (most recent call last):
  File "/home/Lin-Buo-Ren/.local/bin/git-cola", line 56, in <module>
    sys.exit(main())
  File "/home/Lin-Buo-Ren/.local/share/git-cola/lib/cola/main.py", line 31, in main
    return args.func(args)
  File "/home/Lin-Buo-Ren/.local/share/git-cola/lib/cola/main.py", line 284, in cmd_cola
    view = MainView(context.model, settings=args.settings)
  File "/home/Lin-Buo-Ren/.local/share/git-cola/lib/cola/widgets/main.py", line 535, in __init__
    N_('git cola version %s') % version.version())
  File "/home/Lin-Buo-Ren/.local/share/git-cola/lib/cola/widgets/log.py", line 56, in log
    cursor.insertText(prefix + line + '\n')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 6: ordinal not in range(128)
```

## Git Cola
* commit 90af521, post version 2.11
* `git reset --hard` and `git clean -dfx` executed before building
* installation prefix: `${HOME}/.local`

## Python
2.7.12 from Ubuntu software archive

## Operating System
KDE neon 5.11(based on Ubuntu 16.04) AMD64

## Locale
```
LANG=zh_TW.UTF-8
LANGUAGE=zh_TW:zh_CN
LC_CTYPE="zh_TW.UTF-8"
LC_NUMERIC="zh_TW.UTF-8"
LC_TIME="zh_TW.UTF-8"
LC_COLLATE="zh_TW.UTF-8"
LC_MONETARY="zh_TW.UTF-8"
LC_MESSAGES="zh_TW.UTF-8"
LC_PAPER="zh_TW.UTF-8"
LC_NAME="zh_TW.UTF-8"
LC_ADDRESS="zh_TW.UTF-8"
LC_TELEPHONE="zh_TW.UTF-8"
LC_MEASUREMENT="zh_TW.UTF-8"
LC_IDENTIFICATION="zh_TW.UTF-8"
LC_ALL=
```

**Comment by Lin-Buo-Ren** [comment]
I've bisected and here's the result:

```
05e7d4c8abf8ba4e1707330547b5c2abfea95949 is the first bad commit
commit 05e7d4c8abf8ba4e1707330547b5c2abfea95949
Author: David Aguilar <davvid@gmail.com>
Date:   Sat Oct 7 21:55:45 2017 -0700

    log: log: simplify the log time format
    
    Signed-off-by: David Aguilar <davvid@gmail.com>

:040000 040000 469a8f757d56b73d6c5a9f23162ec52c40461a71 a4566c68c1e4b1e61fa01134f2652ba750cd5d9b M    cola
```
