### ISSUE TITLE
raise PythonQtError('No Qt bindings could be found') qtpy.PythonQtError: No Qt bindings could be found

### ISSUE THREAD

**Issue by weilunzhen** [git-cola/git-cola#754]
1. pip3 install spyder3
2.run spyder3 in mac
3.errors occur as following
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/qtpy/__init__.py", line 148, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/spyder3", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/spyder/app/start.py", line 144, in main
    from spyder.app import mainwindow
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 49, in <module>
    requirements.check_qt()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/spyder/requirements.py", line 39, in check_qt
    import qtpy
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/qtpy/__init__.py", line 154, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

Versions and main components

Spyder Version:3
Python Version: 3
Operating system: osx

**Comment by davvid** [comment]
Did you install stuff using homebrew?  I'd suggest installing pyqt5 via homebrew (or do they just call it "pyqt" these days?)

This is the `git-cola` bug tracker, but this seems like a spyder bug report so I'm closing the issue, but I suspect that the solution is the same (install either pyqt or pyside).
