### ISSUE TITLE
Something wrong with OSX install?

### ISSUE THREAD

**Issue by ataiya** [git-cola/git-cola#768]
```
macOS High Sierra 10.13.3
Homebrew 1.5.8
```

Sphinx reports application is created, but then:
~/dev/git-cola: open /Applications/git-cola.app
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/git-cola.app.

Note however, this:
```
~/dev/git-cola: make \
>     PYTHON=$(brew --prefix python3)/bin/python3 \
>     PYTHON_CONFIG=$(brew --prefix python3)/bin/python3-config \
>     SPHINXBUILD=$(brew --prefix sphinx-doc)/bin/sphinx-build \
>     git-cola.app
Traceback (most recent call last):
  File "/Users/atagliasacchi/dev/git-cola/qtpy/__init__.py", line 148, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/git-cola", line 53, in <module>
    from cola.main import main  # pylint: disable=wrong-import-position
  File "/Users/atagliasacchi/dev/git-cola/cola/main.py", line 7, in <module>
    from .app import add_common_arguments
  File "/Users/atagliasacchi/dev/git-cola/cola/app.py", line 15, in <module>
    from qtpy import QtCore
  File "/Users/atagliasacchi/dev/git-cola/qtpy/__init__.py", line 154, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
mkdir -p /Users/atagliasacchi/dev/git-cola/git-cola.app/Contents/MacOS
mkdir -p /Users/atagliasacchi/dev/git-cola/git-cola.app/Contents/Resources
cp contrib/darwin/Info.plist contrib/darwin/PkgInfo /Users/atagliasacchi/dev/git-cola/git-cola.app/Contents
cp contrib/darwin/git-cola /Users/atagliasacchi/dev/git-cola/git-cola.app/Contents/MacOS
cp contrib/darwin/git-cola.icns /Users/atagliasacchi/dev/git-cola/git-cola.app/Contents/Resources
/Library/Developer/CommandLineTools/usr/bin/make prefix=/Users/atagliasacchi/dev/git-cola/git-cola.app/Contents/Resources install install-doc
Traceback (most recent call last):
  File "/Users/atagliasacchi/dev/git-cola/qtpy/__init__.py", line 148, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/git-cola", line 53, in <module>
    from cola.main import main  # pylint: disable=wrong-import-position
  File "/Users/atagliasacchi/dev/git-cola/cola/main.py", line 7, in <module>
    from .app import add_common_arguments
  File "/Users/atagliasacchi/dev/git-cola/cola/app.py", line 15, in <module>
    from qtpy import QtCore
  File "/Users/atagliasacchi/dev/git-cola/qtpy/__init__.py", line 154, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
/usr/local/opt/python/bin/python3 setup.py  build
running build
running build_mo
GNU gettext msgfmt utility not found!
Skip compiling po files.
running build_scripts
/usr/local/opt/python/bin/python3 setup.py --quiet install --prefix=/Users/atagliasacchi/dev/git-cola/git-cola.app/Contents/Resources --force --install-scripts=/Users/atagliasacchi/dev/git-cola/git-cola.app/Contents/Resources/bin --record=build/MANIFEST --install-lib=/Users/atagliasacchi/dev/git-cola/git-cola.app/Contents/Resources/share/git-cola/lib
GNU gettext msgfmt utility not found!
Skip compiling po files.
mkdir -p /Users/atagliasacchi/dev/git-cola/git-cola.app/Contents/Resources/share/icons/hicolor/scalable/apps
ln -s -f /Users/atagliasacchi/dev/git-cola/git-cola.app/Contents/Resources/share/git-cola/icons/git-cola.svg /Users/atagliasacchi/dev/git-cola/git-cola.app/Contents/Resources/share/icons/hicolor/scalable/apps/git-cola.svg
ln -s -f git-cola /Users/atagliasacchi/dev/git-cola/git-cola.app/Contents/Resources/bin/cola
rm -fr /Users/atagliasacchi/dev/git-cola/git-cola.app/Contents/Resources/share/git-cola/lib/git_cola*
rm -fr git_cola.egg-info
/Library/Developer/CommandLineTools/usr/bin/make -C share/doc/git-cola install
mkdir -p /Users/atagliasacchi/dev/git-cola/git-cola.app/Contents/Resources/share/doc/git-cola
install -m 644 *.html /Users/atagliasacchi/dev/git-cola/git-cola.app/Contents/Resources/share/doc/git-cola
install -m 644 *.rst /Users/atagliasacchi/dev/git-cola/git-cola.app/Contents/Resources/share/doc/git-cola
/usr/local/opt/sphinx-doc/bin/sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.7.1
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 5 source files that are out of date
updating environment: 5 added, 0 changed, 0 removed
reading sources... [100%] thanks
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] thanks
generating indices... genindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded.

The HTML pages are in _build/html.
Renaming directory '_sources' -> 'sources'
Renaming directory '_static' -> 'static'
mkdir -p /Users/atagliasacchi/dev/git-cola/git-cola.app/Contents/Resources/share/doc/git-cola/html
rsync -r --delete --delete-excluded --exclude=.buildinfo --exclude=.gitignore _build/html/ /Users/atagliasacchi/dev/git-cola/git-cola.app/Contents/Resources/share/doc/git-cola/html/
/usr/local/opt/sphinx-doc/bin/sphinx-build -b man -d _build/doctrees   . _build/man
Running Sphinx v1.7.1
making output directory...
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
writing... git-cola.1 { } git-dag.1 { }
build succeeded.

The manual pages are in _build/man.
mkdir -p /Users/atagliasacchi/dev/git-cola/git-cola.app/Contents/Resources/share/man/man1
install -m 644 _build/man/git-cola.1 /Users/atagliasacchi/dev/git-cola/git-cola.app/Contents/Resources/share/man/man1
install -m 644 _build/man/git-dag.1 /Users/atagliasacchi/dev/git-cola/git-cola.app/Contents/Resources/share/man/man1
ln -s -f /usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/Resources/Python.app/Contents/MacOS/Python /Users/atagliasacchi/dev/git-cola/git-cola.app/Contents/Resources/git-cola
```

**Comment by davvid** [comment]
The Makefile rules that build `git-cola.app` haven't changed in ages so I'll have to test this out with a new macOS install soon.  The error messages you see are basically saying that homebrew's python cannot find your PyQt5 installation.

I just tweaked how we build `git-cola.app` so it might be worth retrying that.  Please test the latest in master.

Also, if you've ever upgraded from an earlier macOS to a newer version (that happens a lot these days) then I would highly recommend uninstalling the old homebrew formulae and reinstalling them.

e.g. ```

# do this first
brew update

# try to reinstall stuff..  some of these may fail, that's okay
brew unlink git-cola
brew rm git-cola

brew unlink qt
brew rm qt

brew unlink pyqt
brew rm pyqt

# "pyqt" was previously called "pyqt5"
brew unlink pyqt5
brew rm pyqt5

# finally, reinstall the originall stuff
brew install pyqt
brew install git-cola
```

let me know if any of this worked out for you.

**Comment by davvid** [comment]
My mac laptop recently upgraded to high sierra.  I ended up running these two commands to bring things back up to date:

    brew update
    brew upgrade

Using "upgrade" is probably better than fiddling with each package separately.  Can you please let me know if that's working for you?

**Comment by ataiya** [comment]
Yup, just an upgrade was sufficient ;)
