### ISSUE TITLE
Error install on Debian Buster (testing)

### ISSUE THREAD

**Issue by hyperclock** [git-cola/git-cola#837]
after install git-cola on Debian Buster, I got this message.
```
:~$ git-cola
Traceback (most recent call last):
  File "/usr/bin/git-cola", line 55, in <module>
    from cola.main import main
  File "/usr/share/git-cola/lib/cola/main.py", line 7, in <module>
    from . import app
  File "/usr/share/git-cola/lib/cola/app.py", line 13, in <module>
    from . import core
  File "/usr/share/git-cola/lib/cola/core.py", line 9, in <module>
    import distutils.spawn as spawn
ModuleNotFoundError: No module named 'distutils.spawn'

```

I took a lot of time searching, but this seems to fix it.
```
apt install python3-distutils
```

I'm not sure if it was just missing or just needs to installed as an extra depend starting with Deb10

**Comment by davvid** [comment]
Good catch.  I think I'll try to eliminate this external dependency.  My guess is that `distutils` got moved out of the core in python3, whereas in python2 it was part of the main python package.
