### ISSUE TITLE
Git Cola crashes with "TypeError: a bytes-like object is required, not 'str'" in confined environment

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [git-cola/git-cola#849]
This crashed is reproduced in a snap package confined environment ~~, where /etc/gitconfig is not accessible.~~

**UPDATE:** /etc/gitconfig is accessible, but empty

```
Traceback (most recent call last):
  File "/snap/git-cola-brlin/x2/share/git-cola/lib/cola/gitcfg.py", line 467, in color
    r, g, b = struct.unpack(struct_layout, unhex(string))
  File "/snap/git-cola-brlin/x2/share/git-cola/lib/cola/gitcfg.py", line 90, in unhex
    return unhexlify(value.lstrip('#'))
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/git-cola", line 56, in <module>
    sys.exit(main())
  File "/snap/git-cola-brlin/x2/share/git-cola/lib/cola/main.py", line 28, in main
    return args.func(args)
  File "/snap/git-cola-brlin/x2/share/git-cola/lib/cola/main.py", line 298, in cmd_cola
    view = MainView(context, settings=args.settings)
  File "/snap/git-cola-brlin/x2/share/git-cola/lib/cola/widgets/main.py", line 145, in __init__
    fn=lambda dock: diff.Viewer(self.context, parent=dock))
  File "/snap/git-cola-brlin/x2/share/git-cola/lib/cola/qtutils.py", line 765, in create_dock
    widget = fn(dock)
  File "/snap/git-cola-brlin/x2/share/git-cola/lib/cola/widgets/main.py", line 145, in <lambda>
    fn=lambda dock: diff.Viewer(self.context, parent=dock))
  File "/snap/git-cola-brlin/x2/share/git-cola/lib/cola/widgets/diff.py", line 331, in __init__
    self.text = DiffEditor(options, self, context)
  File "/snap/git-cola-brlin/x2/share/git-cola/lib/cola/widgets/diff.py", line 613, in __init__
    DiffTextEdit.__init__(self, parent, numbers=True)
  File "/snap/git-cola-brlin/x2/share/git-cola/lib/cola/widgets/diff.py", line 145, in __init__
    whitespace=whitespace)
  File "/snap/git-cola-brlin/x2/share/git-cola/lib/cola/widgets/diff.py", line 64, in __init__
    self.color_text = qtutils.RGB(cfg.color('text', '030303'))
  File "/snap/git-cola-brlin/x2/share/git-cola/lib/cola/gitcfg.py", line 469, in color
    r, g, b = struct.unpack(struct_layout, unhex(default))
  File "/snap/git-cola-brlin/x2/share/git-cola/lib/cola/gitcfg.py", line 90, in unhex
    return unhexlify(value.lstrip('#'))
TypeError: a bytes-like object is required, not 'str'
```

**Comment by Lin-Buo-Ren** [comment]
Full output with `GIT_COLA_TRACE=true`

```
git -c diff.suppressBlankEmpty=false config --get-all --show-origin -z cola.icontheme
git -c diff.suppressBlankEmpty=false config --null --file /etc/gitconfig --list
git -c diff.suppressBlankEmpty=false config --null --file /home/Lin-Buo-Ren/snap/git-cola-brlin/x4/.gitconfig --list
git -c diff.suppressBlankEmpty=false config --null --file /home/Lin-Buo-Ren/工作空間/個人專案/Snap Packaging for Git Cola/.git/config --list
Traceback (most recent call last):
  File "/snap/git-cola-brlin/x4/share/git-cola/lib/cola/gitcfg.py", line 467, in color
    r, g, b = struct.unpack(struct_layout, unhex(string))
  File "/snap/git-cola-brlin/x4/share/git-cola/lib/cola/gitcfg.py", line 90, in unhex
    return unhexlify(value.lstrip('#'))
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/git-cola-brlin/x4/bin/git-cola", line 56, in <module>
    sys.exit(main())
  File "/snap/git-cola-brlin/x4/share/git-cola/lib/cola/main.py", line 28, in main
    return args.func(args)
  File "/snap/git-cola-brlin/x4/share/git-cola/lib/cola/main.py", line 298, in cmd_cola
    view = MainView(context, settings=args.settings)
  File "/snap/git-cola-brlin/x4/share/git-cola/lib/cola/widgets/main.py", line 145, in __init__
    fn=lambda dock: diff.Viewer(self.context, parent=dock))
  File "/snap/git-cola-brlin/x4/share/git-cola/lib/cola/qtutils.py", line 765, in create_dock
    widget = fn(dock)
  File "/snap/git-cola-brlin/x4/share/git-cola/lib/cola/widgets/main.py", line 145, in <lambda>
    fn=lambda dock: diff.Viewer(self.context, parent=dock))
  File "/snap/git-cola-brlin/x4/share/git-cola/lib/cola/widgets/diff.py", line 331, in __init__
    self.text = DiffEditor(options, self, context)
  File "/snap/git-cola-brlin/x4/share/git-cola/lib/cola/widgets/diff.py", line 613, in __init__
    DiffTextEdit.__init__(self, parent, numbers=True)
  File "/snap/git-cola-brlin/x4/share/git-cola/lib/cola/widgets/diff.py", line 145, in __init__
    whitespace=whitespace)
  File "/snap/git-cola-brlin/x4/share/git-cola/lib/cola/widgets/diff.py", line 64, in __init__
    self.color_text = qtutils.RGB(cfg.color('text', '030303'))
  File "/snap/git-cola-brlin/x4/share/git-cola/lib/cola/gitcfg.py", line 469, in color
    r, g, b = struct.unpack(struct_layout, unhex(default))
  File "/snap/git-cola-brlin/x4/share/git-cola/lib/cola/gitcfg.py", line 90, in unhex
    return unhexlify(value.lstrip('#'))
TypeError: a bytes-like object is required, not 'str'
```

**Comment by Lin-Buo-Ren** [comment]
I found that if I run Git Cola using Python 2 instead of 3, this issue is not reproduced.

**Comment by davvid** [comment]
We'll make this work with python3 as well.  Thanks for the heads-up and version information.
