### ISSUE TITLE
Crashing in spellcheck.py with python 3.7

### ISSUE THREAD

**Issue by lespea** [git-cola/git-cola#857]
Just upgrade to python3.7 via brew (also ensured that I have the latest git-cola including a full reinstall) and whenever I type anything into the "Extended description" text box I get a crash with the following exception:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/git-cola/3.1_1/share/git-cola/lib/cola/widgets/spellcheck.py", line 126, in read
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Cellar/git-cola/3.1_1/share/git-cola/lib/cola/widgets/spellcheck.py", line 213, in highlightBlock
    if not self.spellcheck.check(word_object.group()):
  File "/usr/local/Cellar/git-cola/3.1_1/share/git-cola/lib/cola/widgets/spellcheck.py", line 91, in check
    self.init()
  File "/usr/local/Cellar/git-cola/3.1_1/share/git-cola/lib/cola/widgets/spellcheck.py", line 80, in init
    train(self.read(), self.words)
  File "/usr/local/Cellar/git-cola/3.1_1/share/git-cola/lib/cola/widgets/spellcheck.py", line 34, in train
    for f in features:
RuntimeError: generator raised StopIteration
[1]    45190 abort      git-cola
```

**Comment by davvid** [comment]
For now you can quickly tweak your installation by editing that file and replacing `raise StopIteration` with `return` and that'll fix it.

Otherwise, please try the latest on master.

**Comment by lespea** [comment]
Running the master branch fixed the issue!  Thanks for the quick response :)
