### ISSUE TITLE
git-dag crashes on today's master

### ISSUE THREAD

**Issue by sthalik** [git-cola/git-cola#860]
Today's date is `20180724` and master's top commit is the `144887fc` merge. I'm using Python 3 for Windows i386 and PyQt5 5.10.1.

`git dag` crashes as per,

```
Traceback (most recent call last):
  File "d:\dev\git-cola\cola\widgets\dag.py", line 835, in run
    for c in repo.get():
  File "d:\dev\git-cola\cola\models\dag.py", line 286, in get
    commit = CommitFactory.new(log_entry=log_entry)
  File "d:\dev\git-cola\cola\models\dag.py", line 36, in new
    log_entry=log_entry)
  File "d:\dev\git-cola\cola\models\dag.py", line 121, in __init__
    self.parse(log_entry)
  File "d:\dev\git-cola\cola\models\dag.py", line 127, in parse
    (parents, tags, author, authdate, email, summary) = details
ValueError: not enough values to unpack (expected 6, got 1)
```

The cloned repository is https\:\/\/github\.com/opentrack/opentrack.

Would any particular additional info be of use?

**Comment by sthalik** [comment]
Note, same happens on git-cola repository. Here's my `.gitconfig`:

[dot.gitconfig](https://github.com/git-cola/git-cola/files/2221320/dot.gitconfig.txt)

**Comment by davvid** [comment]
I'm in the middle of a medium-sized refactoring and will get this fixed shortly.  I'll add the data we're getting in this situation to our unit tests too.  Thanks for the heads-up.
