### ISSUE TITLE
Crush when trying do spellcheck

### ISSUE THREAD

**Issue by gelldur** [git-cola/git-cola#886]
I get crush app when i press any letter in commit description. Title is fine.
cola version 3.1

```
Traceback (most recent call last):
  File "/usr/share/git-cola/lib/cola/widgets/spellcheck.py", line 126, in read
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/share/git-cola/lib/cola/widgets/spellcheck.py", line 213, in highlightBlock
    if not self.spellcheck.check(word_object.group()):
  File "/usr/share/git-cola/lib/cola/widgets/spellcheck.py", line 91, in check
    self.init()
  File "/usr/share/git-cola/lib/cola/widgets/spellcheck.py", line 80, in init
    train(self.read(), self.words)
  File "/usr/share/git-cola/lib/cola/widgets/spellcheck.py", line 34, in train
    for f in features:
RuntimeError: generator raised StopIteration
[1]    13083 abort (core dumped)  git-cola
```

**Comment by davvid** [comment]
Thanks for the report.  This was fixed in `v3.2`.  Please verify the fix:

    git clone git://github.com/git-cola/git-cola.git
    ./git-cola/bin/git-cola
