### ISSUE TITLE
git-dag crashes when running form "Visualize Current Branch..."

### ISSUE THREAD

**Issue by jm4R** [git-cola/git-cola#945]
On Linux, I have `git-dag` set as History Browser. When I manually run `git-dag` it works fine, but when I run it from `Visualize Current Branch...` or `Visualize All Branches...` menu, it immediately crashes with error:

    Traceback (most recent call last):
      File "/usr/bin/git-dag", line 92, in <module>
        sys.exit(main())
      File "/usr/bin/git-dag", line 62, in main
        return args.func(args)
      File "/usr/bin/git-dag", line 87, in cmd_dag
        view = git_dag(context.model, args=args, settings=args.settings)
      File "/usr/share/git-cola/lib/cola/widgets/dag.py", line 40, in git_dag
        model = context.model
    AttributeError: 'MainModel' object has no attribute 'model'

**Comment by jm4R** [comment]
After analysis, I found out that `/usr/bin/git-dag` was in the old version. Update must have went wrong.
