### ISSUE TITLE
Crash on start: "source code string cannot contain null bytes"

### ISSUE THREAD

**Issue by piegamesde** [git-cola/git-cola#948]
When I run `git-cola`, I get:

```
Traceback (most recent call last):
  File "/usr/bin/git-cola", line 53, in <module>
    from cola.main import main
  File "/usr/share/git-cola/lib/cola/main.py", line 6, in <module>
    from . import app
  File "/usr/share/git-cola/lib/cola/app.py", line 15, in <module>
    from qtpy import QtCore
  File "/usr/share/git-cola/lib/qtpy/__init__.py", line 125, in <module>
    from PyQt5.QtCore import PYQT_VERSION_STR as PYQT_VERSION  # analysis:ignore
ValueError: source code string cannot contain null bytes
```

I've tried both packages `git-cola` and `git-cola-git` from the AUR and both fail. Cloning the repository and running it fails as well.

**Comment by piegamesde** [comment]
I got it to work by installing `python2-pyqt5` and then running it with `python2`. So it seems to be a dependency issue, even if the error message is quite cryptic.

**Comment by piegamesde** [comment]
Reinstalling python fixed the issue, so it probably wasn't a bug in the first place
